resources:
- name: code
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-v7.git
    branch: main


jobs:
- name: print
  plan:
  - get: code
    trigger: true
  - task: hello-world
    file: code/tasks/hello-world.yaml
    params:
      message: ((message))