resources:
- name: code
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-v7.git
    branch: main

jobs:
- name: configure 
  plan:
  - get: code
    trigger: true
  - set_pipeline: self
    file: code/pipeline.yaml
  - load_var: config
    file: code/message.json
  - set_pipeline: hello-world
    file: code/hello-pipeline.yaml
    instance_vars:
      message: ((.:config.message))
