resources:
- name: code
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-v7.git
    branch: main

jobs:
- name: configure-self
  plan:
  - get: code
    trigger: true
  - set_pipeline: self
    file: code/pipeline.yaml
- name: configure-instances
  plan:
  - get: code
    trigger: true
    passed:
    - configure-self
  - load_var: config
    file: code/message.json
  - set_pipeline: hello-world
    file: code/hello-pipeline.yaml
    instance_vars:
      message: ((.:config.message))
      something: ((.:something))
    across:
    - var: something
      values: [1, 2, 3, 4, 5]
