platform: linux

inputs:
- name: code

outputs:
- name: build-artifacts
  path: code/target

caches:
- path: $HOME/.m2/repository

run:
  dir: code
  path: mvn
  args:
  - "package"
  - "jib:buildTar"
  - "-f"
  - "pom.xml" 