resources:
- name: code
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-code.git
    branch: main

- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-pipeline.git
    branch: main
    paths:
    - tasks

- name: maven
  icon: docker
  type: registry-image
  check_every: 168h
  source:
    repository: maven

- name: busybox
  icon: docker
  type: registry-image
  check_every: 168h
  source:
    repository: busybox
    
- name: app-container
  icon: docker
  type: registry-image
  source:
    repository: ghcr.io/etone/spring-boot-hello-world
    username: etone
    password: ((git-package-token))


jobs:
- name: generate-metadata
  plan:
  - get: code
    trigger: true
  - get: ci
- name: build-and-test
  plan:
  - in_parallel:  
    - get: code
      passed:
      - generate-metadata
      trigger: true
    - get: ci
      passed:
      - generate-metadata
    - get: maven
  - task: build-jar-and-container
    file: ci/tasks/build-java-maven.yaml
    image: maven
  - put: app-container
    inputs:
    - build-artifacts
    params:
      image: build-artifacts/jib-image.tar
      version: v1
- name: deploy
  plan:
  - in_parallel:  
    - get: ci
      passed:
      - generate-metadata
    - get: app-container
      passed:
      - build-and-test
      params:
        format: rootfs
      trigger: true
    - get: busybox
  - task: print-info
    file: ci/tasks/print-container-info.yaml
    image: busybox
    input_mapping:
      container: app-container
