resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  icon: github
  source:
    repository: Etone/concourse-demo-pipeline
    number: ((number))


- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-pipeline.git
    branch: main
    paths:
    - tasks

- name: maven
  icon: docker
  type: registry-image
  check_every: 168h
  source:
    repository: maven
    
jobs:
- name: build-and-test
  plan:
  - in_parallel:  
    - get: pull-request
      trigger: true
    - get: ci
    - get: maven
  - task: build-jar-and-container
    file: ci/tasks/build-java-maven.yaml
    image: maven
    input_mapping:
      code: pull-request
  
