resources:
- name: code
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-code.git
    branch: main

- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-pipeline.git
    branch: main
    paths:
    - tasks

- name: maven
  type: registry-image
  source:
    repository: busybox
    tag: 1.33
    


jobs:
- name: generate-metadata
  plan:
  - get: code
    trigger: true
  - get: ci
- name: build-and-test
  plan:
  - in_parallel:  
    - get: code
      passed:
      - generate-metadata
      trigger: true
    - get: ci
      passed:
      - generate-metadata
  - task: build
    file: ci/tasks/build-java-maven.yaml
    image: maven
- name: deploy
  plan:
  - get: ci
    passed:
    - generate-metadata