resources:
- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-pipeline.git
    branch: main
    paths:
    - pipelines

jobs:
- name: configure-self
  plan:
  - get: ci
    trigger: true
  - set_pipeline: self
    file: ci/pipelines/reconfigure.yaml
- name: configure-prs
  plan:
  - in_parallel:
    - get: ci
      trigger: true
      passed:
      - configure-self
  - across:
    - var: branch
      values: [language, bye-world]
    set_pipeline: branches
    file: ci/pipelines/build-credless.yml
    instance_vars: 
      branch: ((.:branch))
