resource_types:
- name: git-branches
  type: registry-image
  source:
    repository: aoldershaw/git-branches-resource

resources:
- name: branches
  type: git-branches
  source:
    uri: git@github.com:concourse/concourse.git
    branch_regex: snapshot/.*

- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/Etone/concourse-demo-pipeline.git
    branch: main
    paths:
    - pipelines

jobs:
- name: configure-self
  plan:
  - get: ci
    trigger: true
  - set_pipeline: self
    file: ci/pipelines/reconfigure.yaml
- name: configure-prs
  plan:
  - in_parallel:
    - get: ci
      trigger: true
      passed:
      - configure-self
    - get: branches
      trigger: true
  - load_var: branches
    file: branches/branches.json
  - across:
    - var: branch
      values: ((.:branches))
    set_pipeline: branches
    file: ci/pipelines/build-credless.yml
    instance_vars: 
      branch: ((.:branch))
